-- MySQL Script generated by MySQL Workbench
-- Tue Apr 27 13:29:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema kupi_sebi_doniraj_drugom
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `kupi_sebi_doniraj_drugom` ;

-- -----------------------------------------------------
-- Schema kupi_sebi_doniraj_drugom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kupi_sebi_doniraj_drugom` ;
USE `kupi_sebi_doniraj_drugom` ;

-- -----------------------------------------------------
-- Table `kupi_sebi_doniraj_drugom`.`Korisnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kupi_sebi_doniraj_drugom`.`Korisnik` ;

CREATE TABLE IF NOT EXISTS `kupi_sebi_doniraj_drugom`.`Korisnik` (
  `idKorisnik` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(45) NOT NULL,
  `grad` VARCHAR(45) NOT NULL,
  `telefon` VARCHAR(45) NOT NULL,
  `korisničko ime` VARCHAR(20) NOT NULL,
  `lozinka` VARCHAR(20) NOT NULL,
  `pol` CHAR(1) NOT NULL,
  PRIMARY KEY (`idKorisnik`),
  UNIQUE INDEX `korisničko ime_UNIQUE` (`korisničko ime` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kupi_sebi_doniraj_drugom`.`Kompanija`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kupi_sebi_doniraj_drugom`.`Kompanija` ;

CREATE TABLE IF NOT EXISTS `kupi_sebi_doniraj_drugom`.`Kompanija` (
  `PIB` CHAR(9) NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `registarski broj` VARCHAR(15) NOT NULL,
  `adresa` VARCHAR(45) NOT NULL,
  `telefon` VARCHAR(45) NOT NULL,
  `lozinka` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`PIB`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kupi_sebi_doniraj_drugom`.`Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kupi_sebi_doniraj_drugom`.`Admin` ;

CREATE TABLE IF NOT EXISTS `kupi_sebi_doniraj_drugom`.`Admin` (
  `korisničko ime` VARCHAR(45) NOT NULL,
  `lozinka` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`korisničko ime`),
  UNIQUE INDEX `korisničko ime_UNIQUE` (`korisničko ime` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kupi_sebi_doniraj_drugom`.`Kategorija`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kupi_sebi_doniraj_drugom`.`Kategorija` ;

CREATE TABLE IF NOT EXISTS `kupi_sebi_doniraj_drugom`.`Kategorija` (
  `IdKategorije` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdKategorije`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kupi_sebi_doniraj_drugom`.`Fondacija`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kupi_sebi_doniraj_drugom`.`Fondacija` ;

CREATE TABLE IF NOT EXISTS `kupi_sebi_doniraj_drugom`.`Fondacija` (
  `idFondacija` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(45) NOT NULL,
  `račun` CHAR(20) NOT NULL,
  `opis` VARCHAR(256) NOT NULL,
  `logo` BLOB NOT NULL,
  `iznos` DOUBLE NULL,
  PRIMARY KEY (`idFondacija`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kupi_sebi_doniraj_drugom`.`Licitacija`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kupi_sebi_doniraj_drugom`.`Licitacija` ;

CREATE TABLE IF NOT EXISTS `kupi_sebi_doniraj_drugom`.`Licitacija` (
  `idLicitacija` INT NOT NULL,
  `naziv_stvari` VARCHAR(45) NOT NULL,
  `opis` VARCHAR(256) NOT NULL,
  `početna_cena` INT NOT NULL,
  `trajanje` INT NOT NULL,
  `slika` BLOB NOT NULL,
  `aktivna` BIT(1) NOT NULL DEFAULT 0,
  `Kategorija_IdKategorije` INT NOT NULL,
  `Fondacija_idFondacija` INT NOT NULL,
  PRIMARY KEY (`idLicitacija`),
  INDEX `fk_Licitacija_Kategorija_idx` (`Kategorija_IdKategorije` ASC) VISIBLE,
  INDEX `fk_Licitacija_Fondacija1_idx` (`Fondacija_idFondacija` ASC) VISIBLE,
  CONSTRAINT `fk_Licitacija_Kategorija`
    FOREIGN KEY (`Kategorija_IdKategorije`)
    REFERENCES `kupi_sebi_doniraj_drugom`.`Kategorija` (`IdKategorije`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Licitacija_Fondacija1`
    FOREIGN KEY (`Fondacija_idFondacija`)
    REFERENCES `kupi_sebi_doniraj_drugom`.`Fondacija` (`idFondacija`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kupi_sebi_doniraj_drugom`.`Trenutne_cene`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kupi_sebi_doniraj_drugom`.`Trenutne_cene` ;

CREATE TABLE IF NOT EXISTS `kupi_sebi_doniraj_drugom`.`Trenutne_cene` (
  `Cena` INT NOT NULL,
  `Licitacija_idLicitacija` INT NOT NULL,
  `Korisnik_idKorisnik` INT NOT NULL,
  INDEX `fk_Trenutne_cene_Licitacija1_idx` (`Licitacija_idLicitacija` ASC) VISIBLE,
  INDEX `fk_Trenutne_cene_Korisnik1_idx` (`Korisnik_idKorisnik` ASC) VISIBLE,
  PRIMARY KEY (`Licitacija_idLicitacija`),
  CONSTRAINT `fk_Trenutne_cene_Licitacija1`
    FOREIGN KEY (`Licitacija_idLicitacija`)
    REFERENCES `kupi_sebi_doniraj_drugom`.`Licitacija` (`idLicitacija`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trenutne_cene_Korisnik1`
    FOREIGN KEY (`Korisnik_idKorisnik`)
    REFERENCES `kupi_sebi_doniraj_drugom`.`Korisnik` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kupi_sebi_doniraj_drugom`.`Recenzija`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kupi_sebi_doniraj_drugom`.`Recenzija` ;

CREATE TABLE IF NOT EXISTS `kupi_sebi_doniraj_drugom`.`Recenzija` (
  `idRecenzija` INT NOT NULL AUTO_INCREMENT,
  `Ocena` INT NOT NULL,
  `Komentar` VARCHAR(256) NULL,
  `Korisnik_idKorisnik` INT NOT NULL,
  PRIMARY KEY (`idRecenzija`),
  INDEX `fk_Recenzija_Korisnik1_idx` (`Korisnik_idKorisnik` ASC) VISIBLE,
  CONSTRAINT `fk_Recenzija_Korisnik1`
    FOREIGN KEY (`Korisnik_idKorisnik`)
    REFERENCES `kupi_sebi_doniraj_drugom`.`Korisnik` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kupi_sebi_doniraj_drugom`.`Uplata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kupi_sebi_doniraj_drugom`.`Uplata` ;

CREATE TABLE IF NOT EXISTS `kupi_sebi_doniraj_drugom`.`Uplata` (
  `idUplata` INT NOT NULL AUTO_INCREMENT,
  `uplatilac` VARCHAR(45) NOT NULL,
  `valuta` VARCHAR(5) NOT NULL,
  `iznos` INT NOT NULL,
  `račun primaoca` CHAR(20) NOT NULL,
  `svrha uplate` INT NOT NULL,
  `primalac` INT NOT NULL,
  PRIMARY KEY (`idUplata`),
  INDEX `fk_Uplata_Licitacija1_idx` (`svrha uplate` ASC) VISIBLE,
  INDEX `fk_Uplata_Fondacija1_idx` (`primalac` ASC) VISIBLE,
  CONSTRAINT `fk_Uplata_Licitacija1`
    FOREIGN KEY (`svrha uplate`)
    REFERENCES `kupi_sebi_doniraj_drugom`.`Licitacija` (`idLicitacija`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uplata_Fondacija1`
    FOREIGN KEY (`primalac`)
    REFERENCES `kupi_sebi_doniraj_drugom`.`Fondacija` (`idFondacija`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
